-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 22:12:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pivdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pivdb` ;

-- -----------------------------------------------------
-- Schema pivdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pivdb` DEFAULT CHARACTER SET utf8 ;
USE `pivdb` ;

-- -----------------------------------------------------
-- Table `pivdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`user` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL,
  `role` INT(11) NOT NULL,
  `pass` VARCHAR(256) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pivdb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`post` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` INT(11) NOT NULL,
  `updated` TINYINT(10) NOT NULL,
  `postkey` VARCHAR(20) NULL DEFAULT NULL,
  `userId` INT(11) NOT NULL,
  `staffId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pivdb`.`audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`audit` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`audit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action` TEXT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `userId` INT(11) NULL,
  `postId` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pivdb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`contact` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`contact` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` TEXT NULL DEFAULT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `postId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pivdb`.`conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`conversation` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`conversation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `data` TEXT NOT NULL,
  `postId` INT(11) NOT NULL,
  `reply` TINYINT(4) NOT NULL,
  `userId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pivdb`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`email` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`email` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `userId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
