-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 15:04:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pivdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pivdb` ;

-- -----------------------------------------------------
-- Schema pivdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pivdb` DEFAULT CHARACTER SET utf8 ;
USE `pivdb` ;

-- -----------------------------------------------------
-- Table `pivdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`User` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`User` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DisplayName` VARCHAR(45) NULL,
  `Role` INT NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  `Salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pivdb`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`Email` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`Email` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(80) NULL,
  `Date` DATETIME NOT NULL,
  `Code` VARCHAR(45) NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Email_User_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Email_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `pivdb`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pivdb`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`Post` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`Post` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Status` INT NOT NULL,
  `Updated` TINYINT(10) NOT NULL,
  `Key` VARCHAR(20) NULL,
  `UserId` INT NOT NULL,
  `StaffId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Post_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Post_User2_idx` (`StaffId` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `pivdb`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_User2`
    FOREIGN KEY (`StaffId`)
    REFERENCES `pivdb`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pivdb`.`Audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`Audit` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`Audit` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Action` VARCHAR(50) NOT NULL,
  `UserId` INT NOT NULL,
  `PostId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Audit_User1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Audit_Post1_idx` (`PostId` ASC) VISIBLE,
  CONSTRAINT `fk_Audit_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `pivdb`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audit_Post1`
    FOREIGN KEY (`PostId`)
    REFERENCES `pivdb`.`Post` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pivdb`.`Conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`Conversation` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`Conversation` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `Data` TEXT NOT NULL,
  `PostId` INT NOT NULL,
  `reply` TINYINT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Conversation_Post1_idx` (`PostId` ASC) VISIBLE,
  INDEX `fk_Conversation_User1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Conversation_Post1`
    FOREIGN KEY (`PostId`)
    REFERENCES `pivdb`.`Post` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversation_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `pivdb`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pivdb`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pivdb`.`Contact` ;

CREATE TABLE IF NOT EXISTS `pivdb`.`Contact` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Address` TEXT NULL,
  `Number` VARCHAR(45) NULL,
  `PostId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Contact_Post1_idx` (`PostId` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_Post1`
    FOREIGN KEY (`PostId`)
    REFERENCES `pivdb`.`Post` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
